export const dummyTestimonials = [
  {
    packageId: "PKG12345",
    bookingId: "BK12345",
    name: "John Doe",
    country: "Japan",
    duration: "10 days",
    travelType: "Adventure",
    travelTags: ["Hiking", "Nature", "Photography"],
    accommodations: "Hotel Tokyo",
    transportationUsed: "Train, Bus",
    activities: "Mount Fuji, Tokyo Tower, Kyoto Temples",
    demographic: {
      age: "28",
      gender: "Male",
      nationality: "USA",
    },
    language: "English, Japanese",
    socialMediaHandle: "@johnny_adventures",
    testimonial:
      "Amazing experience in Japan. The people, culture, and scenery were extraordinary!",
    mediaType: "photo",
    media: "https://via.placeholder.com/150",
    rating: 5,
    dateOfTravel: "2024-05-10",
    favoriteExperience: "Climbing Mount Fuji at sunrise.",
    suggestionsForFutureTravelers:
      "Try to learn some Japanese phrases, it makes the experience richer!",
  },
  {
    packageId: "PKG67890",
    bookingId: "BK67890",
    name: "Jane Smith",
    country: "France",
    duration: "7 days",
    travelType: "Leisure",
    travelTags: ["Romance", "Sightseeing", "Food"],
    accommodations: "Le Meridien Paris",
    transportationUsed: "Taxi, Metro",
    activities: "Eiffel Tower, Louvre Museum, Seine River Cruise",
    demographic: {
      age: "34",
      gender: "Female",
      nationality: "UK",
    },
    language: "English, French",
    socialMediaHandle: "@janes_journeys",
    testimonial:
      "Paris was a dream come true! The food, culture, and atmosphere were magical.",
    mediaType: "video",
    media: "https://via.placeholder.com/150",
    rating: 4,
    dateOfTravel: "2023-10-15",
    favoriteExperience: "The Seine River Cruise at night was breathtaking.",
    suggestionsForFutureTravelers:
      "Take a guided tour of the Louvre to see all the must-see art pieces.",
  },
  {
    packageId: "PKG11223",
    bookingId: "BK11223",
    name: "Ahmed Ali",
    country: "Egypt",
    duration: "12 days",
    travelType: "Cultural",
    travelTags: ["History", "Ancient Sites", "Exploration"],
    accommodations: "Pyramids View Hotel",
    transportationUsed: "Bus, Camel",
    activities: "Pyramids of Giza, Nile River, Egyptian Museum",
    demographic: {
      age: "45",
      gender: "Male",
      nationality: "Egyptian",
    },
    language: "Arabic, English",
    socialMediaHandle: "@explore_with_ahmed",
    testimonial:
      "Visiting the Pyramids and cruising the Nile were life-changing experiences.",
    mediaType: "photo",
    media: "https://via.placeholder.com/150",
    rating: 5,
    dateOfTravel: "2024-01-20",
    favoriteExperience: "Riding a camel by the Pyramids.",
    suggestionsForFutureTravelers:
      "Book a Nile cruise for a peaceful view of the landmarks.",
  },
  {
    packageId: "PKG33456",
    bookingId: "BK33456",
    name: "Sarah Lee",
    country: "Australia",
    duration: "14 days",
    travelType: "Family Vacation",
    travelTags: ["Beaches", "Wildlife", "Nature"],
    accommodations: "Sydney Harbour Hotel",
    transportationUsed: "Car, Ferry",
    activities: "Great Barrier Reef, Bondi Beach, Sydney Opera House",
    demographic: {
      age: "40",
      gender: "Female",
      nationality: "Canada",
    },
    language: "English",
    socialMediaHandle: "@sarah_familytrips",
    testimonial:
      "A perfect family vacation in Australia! Beautiful beaches and stunning wildlife.",
    mediaType: "photo",
    media: "https://via.placeholder.com/150",
    rating: 4,
    dateOfTravel: "2023-12-05",
    favoriteExperience: "Snorkeling in the Great Barrier Reef.",
    suggestionsForFutureTravelers:
      "Make sure to visit Bondi Beach early in the morning to avoid crowds.",
  },
  {
    packageId: "PKG99887",
    bookingId: "BK99887",
    name: "Emily Johnson",
    country: "Italy",
    duration: "8 days",
    travelType: "Solo Travel",
    travelTags: ["History", "Food", "Culture"],
    accommodations: "Rome Central Hostel",
    transportationUsed: "Walking, Metro",
    activities: "Colosseum, Roman Forum, Vatican City",
    demographic: {
      age: "26",
      gender: "Female",
      nationality: "USA",
    },
    language: "English, Italian",
    socialMediaHandle: "@emily_travelista",
    testimonial:
      "Italy’s rich history and vibrant food scene made my solo trip unforgettable.",
    mediaType: "video",
    media: "https://via.placeholder.com/150",
    rating: 5,
    dateOfTravel: "2024-04-12",
    favoriteExperience:
      "Visiting Vatican City and exploring the Sistine Chapel.",
    suggestionsForFutureTravelers:
      "Learn a few Italian phrases to enhance your experience.",
  },
];
