export const transportationOptions = [
  "Airplane",
  "Train",
  "Metro/Subway",
  "Taxi",
  "Ride-Sharing",
  "Bus",
  "Rental Car",
  "Bicycle",
  "Ferry/Boat",
  "Walking",
];

export const languages = [
  "English",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Japanese",
  "Italian",
  "Portuguese",
  "Arabic",
  "Bangla",
];
export const TravelTags = [
  "Adventure",
  "Beach",
  "Cultural",
  "Romance",
  "Sightseeing",
  "Food",
  "Luxury",
  "Nature",
  "Historical",
  "Wildlife",
];

export const accommodations = [
  "Luxury Resort",
  "Boutique Hotel",
  "Resort & Spa",
  "Business Hotel",
  "Budget Hotel",
  "Airbnb Apartment",
  "Hostel Dormitory",
  "Bed & Breakfast",
  "Overwater Bungalow",
  "Eco-Lodge",
];

export const activities = [
  "Shibuya Crossing Experience 🚶‍♂️",
  "Explore Sensoji Temple in Asakusa 🏯",
  "Take a Boat Ride on Lake Ashi 🚤",
  "Visit the Imperial Palace 🏰",
  "Cherry Blossom Viewing at Ueno Park 🌸",
  "Roppongi Hills Observatory 🏙️",
  "Take a Sushi Making Class 🍣",
  "Walk Through Odaiba Seaside Park 🌊",
  "Visit the Tokyo National Museum 🖼️",
  "Explore Ghibli Museum in Mitaka 🎬",
  "Christ the Redeemer Statue 🗿",
  "Sugarloaf Mountain Hike 🏞️",
  "Iguazu Falls Visit 🌊",
  "Pantanal Wildlife Safari 🦜",
  "Rio Carnival Parade 🎉",
  "Amazon Rainforest Tour 🌳",
  "Copacabana Beach Relaxation 🏖️",
  "Sao Paulo Cultural Visit 🖼️",
  "Brazilian Samba Dance 🎶",
  "Florianopolis Island Exploration 🏝️",
];

export const destinations = [
  "France",
  "kenya",
  "Kyoto",
  "Maldives",
  "Dubai",
  "Phuket",
  "Rome",
  "Cape Town",
  "Barcelona",
  "Maui",
  "Prague",
  "Istanbul",
  "Amsterdam",
  "Seoul",
  "Rio de Janeiro",
  "New York",
  "London",
  "Bangkok",
  "Sydney",
  "Venice",
  "Cairo",
  "Marrakech",
  "Buenos Aires",
  "Lisbon",
  "Madrid",
  "Zurich",
  "Vienna",
  "Hong Kong",
  "Singapore",
  "Los Angeles",
  "Tokyo",
  "Bora Bora",
  "Santorini",
  "Moscow",
  "Bangladesh",
  "Dublin",
  "Edinburgh",
  "Toronto",
  "Havana",
  "Oslo",
  "Stockholm",
  "Kuala Lumpur",
  "Beijing",
  "Florence",
  "Mexico City",
  "Shanghai",
  "Hanoi",
  "Athens",
  "Jakarta",
  "Manila",
  "Budapest",
  "Doha",
  "Lima",
  "Colombo",
  "Kathmandu",
  "Helsinki",
  "Brussels",
  "Vancouver",
  "San Francisco",
  "Chicago",
  "Seville",
  "Nice",
  "Bergen",
  "Reykjavik",
];
